### ISSUE TITLE
Missing utils module

### ISSUE THREAD

**Issue by tlack** [alexblattner/multidiffusion#1]
Eager to try out your interesting code here, but getting stuck on the utils import:

```
from utils.Loras import load_lora_weights, unload_lora_weights                                                                                                                                                                                              from utils import kohya_lora_loader
```

Where can I find this utils module?

Thanks in advance,
t

**Comment by alexblattner** [comment]
@tlack tag me next time because I didn't see this at all haha
I made an update. I removed this code because I deemed it useless and it's a remnant from earlier versions. If you have more questions, feel free to ask
